packages:
  ubuntu:
    common:
      packages:
        - python3-setuptools
        - zlib1g-dev
        - openssh-server
        - wget
        - curl
        - dnsmasq
        - nmap
        - ovmf
        - patch
        - psmisc
        - libvirt-clients
        - libvirt-dev
        - bridge-utils
        - jq
        - unzip
        - genisoimage
        - qemu-kvm
        - libguestfs-tools
        - gir1.2-polkit-1.0
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
        - apache2-utils
    podman:
      packages:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common
    focal_jammy:
      packages:
        - apparmor
        - apparmor-profiles-extra
        - apparmor-utils
        - libvirt-daemon
        - libvirt-daemon-system
        - libssl-dev
        - netcat
    noble:
      packages:
        - apparmor
        - apparmor-profiles-extra
        - apparmor-utils
        - libvirt-daemon
        - libvirt-daemon-system
        - libssl-dev
        - netcat-traditional
    pip3:
    - python-apt
    - kubernetes==25.3.0
    - pyYAML
    - virtualbmc
    - lxml
    - netaddr
    - libvirt-python
    - six
    - docker-py
    - jmespath
    - passlib
    ipv6:
      - jool-dkms
      - jool-tools
      - bind9
  centos:
    common:
      packages:
        - bind-utils
        - curl
        - dnsmasq
        - edk2-ovmf
        - firewalld
        - genisoimage
        - httpd-tools
        - jq
        - libguestfs-tools
        - libguestfs-tools
        - libvirt
        - libvirt-daemon-kvm
        - libvirt-devel
        - NetworkManager
        - nmap
        - patch
        - podman
        - polkit-pkla-compat
        - psmisc
        - python3-bcrypt
        - python3-libvirt
        - python3-lxml
        - python3-netaddr
        - python3-requests-oauthlib
        - python3-six
        - qemu-img
        - qemu-kvm
        - unzip
        - vim-enhanced
        - virt-install
        - wget
    pip3:
      - flask_oauthlib==0.9.6
      - jmespath
      - kubernetes==25.3.0
      - passlib
TEMPLATES_PATH: "{{ metal3_dir }}/vm-setup/roles/packages_installation/files"
CONTAINER_RUNTIME: "{{ lookup('env', 'CONTAINER_RUNTIME') }}"
OS_VERSION_ID: "{{ lookup('env', 'OS_VERSION_ID') }}"
REGISTRY: "{{ lookup('env', 'REGISTRY') }}"
DOCKER_IPV6_SUPPORT: "{{ lookup('env', 'DOCKER_USE_IPV6_INTERNALLY') | default('false', true) }}"
ENABLE_NAT64: "{{ lookup('env', 'ENABLE_NAT64') | default('false', true) }}"
DNS_UPSTREAM: "{{ lookup('env', 'DNS_UPSTREAM') | default('10.1.0.2', true) }}"
DNS64_PREFIX: "{{ lookup('env', 'DNS64_PREFIX') | default('64:ff9b::/96', true) }}"
# Local DNS is only used in IPv6 only env
LOCAL_DNS_V4: "{{ lookup('env', 'LOCAL_DNS_V4') | default('127.0.0.1', true) }}"
LOCAL_DNS_V6: "{{ lookup('env', 'LOCAL_DNS_V6') | default('::1', true) }}"
