apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    # We cannot run Ironic with more than one replica at a time. The recreate
    # strategy makes sure that the old pod is gone before a new is started.
    type: Recreate
  selector:
    matchLabels:
      name: ironic
  template:
    metadata:
      labels:
        name: ironic
    spec:
      containers:
      - name: ironic
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        command:
        - /bin/runironic
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0 # ironic
          runAsGroup: 0 # ironic
      - name: ironic-log-watch
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        command:
        - /bin/runlogwatch.sh
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0 # ironic
          runAsGroup: 0 # ironic
      - name: ironic-httpd
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        command:
        - /bin/runhttpd
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0 # ironic
          runAsGroup: 0 # ironic
      initContainers:
      - name: ironic-ipa-downloader
        image: quay.io/metal3-io/ironic-ipa-downloader
        imagePullPolicy: Always
        command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0 # ironic
          runAsGroup: 0 # ironic
      volumes:
      - name: ironic-data-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 0
---
apiVersion: v1
kind: Service
metadata:
  name: expose-ironic-to-provisioning-network
spec:
  type: NodePort
  selector:
    name: ironic
  ports:
    - name: ironic
      port: 6385
      targetPort: 6385
      nodePort: 30085
    - name: inspector
      port: 5050
      targetPort: 5050
      nodePort: 30050
    - name: httpd
      port: 30080
      targetPort: 30080
      nodePort: 30080