---
- name: t
  hosts: localhost
  vars:
  - CLUSTER_NAME: test1
  - NAMESPACE: metal3
  - NUMBER_OF_BMH_MD: "1"
  tasks:
  - name: t
    k8s:
      api_version: cluster.x-k8s.io/v1alpha3
      kind: MachineDeployment
      name: "{{ CLUSTER_NAME }}"
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
      definition:
        spec:
          replicas: "{{ NUMBER_OF_BMH_MD | int }}"
