apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
  # - ../../../../baremetal-operator/config/default
  # - ../../../../baremetal-operator/config/namespace
  - BMOREPO/config/default?ref=BMOCOMMIT
  - BMOREPO/config/namespace?ref=BMOCOMMIT

# components:
# - components/basic-auth
# - components/tls

configMapGenerator:
  - name: ironic
    behavior: replace
    envs:
      - ironic.env

images:
  - name: quay.io/metal3-io/baremetal-operator
    newName: BAREMETAL_OPERATOR_IMAGE
    newTag: bmo_tag
