---
- name: v1alpha3 integration test
  hosts: virthost
  connection: local
  gather_facts: true
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - import_role:
        name: v1a3_integration_test
