M3PATH := "$(dirname "$(readlink -f "${0}")")/../../"
# This needs to be moved to upgrade.sh and different value should be set before
# each use case.
# NUM_OF_MASTER_REPLICAS := 1
# NUM_OF_WORKER_REPLICAS := 1
