---
- name: "Generate templates for v1alpha3"
  include: "{{ item }}.yml"
  with_items:
    - generate_templates

- name: "{{ CAPI_VERSION }} deployment"
  include: "{{ item }}.yml"
  with_items:
    - provision_cluster
    - download_image
    - provision_controlplane
    - provision_worker
    - verify
    - deprovision_worker
    - deprovision_controlplane
    - deprovision_cluster
    - cleanup
  when: v1aX_integration_test_action == "ci_test"

- name: "{{ CAPI_VERSION }} cluster provisioning"
  include: "provision_cluster.yml"
  when: v1aX_integration_test_action == "provision_cluster"

- name: "{{ CAPI_VERSION }} controlplane node provisioning"
  include: "{{ item }}.yml"
  with_items:
    - download_image
    - provision_controlplane
  when: v1aX_integration_test_action == "provision_controlplane"

- name: "{{ CAPI_VERSION }} worker node provisioning"
  include: "{{ item }}.yml"
  with_items:
    - download_image
    - provision_worker
  when: v1aX_integration_test_action == "provision_worker"

- name: "{{ CAPI_VERSION }} pivoting"
  include: "{{ item }}.yml"
  with_items:
    - verify
    - move
    - move_cleanup
  when: v1aX_integration_test_action == "pivoting"  

- name: "{{ CAPI_VERSION }} cluster deprovisioning"
  include: deprovision_cluster.yml
  when: v1aX_integration_test_action == "deprovision_cluster"

- name: "{{ CAPI_VERSION }} controlplane node deprovisioning"
  include: deprovision_controlplane.yml
  when: v1aX_integration_test_action == "deprovision_controlplane"

- name: "{{ CAPI_VERSION }} worker node deprovisioning"
  include: deprovision_worker.yml
  when: v1aX_integration_test_action == "deprovision_worker"

- name: Node remediation
  include: remediation.yml
  when: v1aX_integration_test_action == "remediation"

- name: "Provisioning for feature_tests"
  include: "{{ item }}.yml"
  with_items:
    - provision_cluster
    - provision_worker
    - provision_controlplane
    - verify
  when: v1aX_integration_test_action == "feature_test_provisioning"

- name: "Deprovisioning for feature_tests"
  include: "{{ item }}.yml"
  with_items:
    - deprovision_worker
    - deprovision_controlplane
    - deprovision_cluster
    - cleanup
  when: v1aX_integration_test_action == "feature_test_deprovisioning"
